### ISSUE TITLE
Some releases require db:migrate and assets:precompile

### ISSUE THREAD

**Issue by mxroo** [mitchellurgero/fediwiki#2]
Thank you so much for your documentation work!

The [Mastodon 1.3 upgrade](https://github.com/tootsuite/mastodon/releases/tag/v1.3) doesn't work properly with the upgrade script due to needing to run other commands that your documentation lists as install commands. After I ran the upgrade script, my instance wasn't working. Once I stopped the container, ran these commands and restarted the container and nginx, everything was fine.

> - This release includes database migrations, that means you need to run RAILS_ENV=production bundle exec rails db:migrate (in Docker: docker-compose run --rm web rails db:migrate)
> - This release includes changes to assets, that means you need to run RAILS_ENV=production bundle exec rails assets:precompile (in Docker: docker-compose run --rm web rails assets:precompile)

**Comment by mitchellurgero** [comment]
Hey @mxroo ! Thanks for opening an issue an letting me know! but due to the nature of that release for Mastodon, and the fact that it is very specific, the update script does not run that. However, in the tutorial there is a FAQ/Basic troubleshooting that does include those commands for specific situations! (However - looking at the update_script.sh on fediwiki.info, those commands are in there.) Please make sure you have the latest update_script! 

But thank you for the comments - I might make a note about those commands in a section specific to those commands.
:)

**Comment by mitchellurgero** [comment]
I went ahead and updated the tutorial. It will be a minute before it propagates to github servers.

**Comment by mxroo** [comment]
Thank you again, for all your work and your prompt reply!

**Comment by mitchellurgero** [comment]
No thank you! It is people like you that help keep the fediverse, and fediwiki.info working! Keep on keepin' on friend!
